Landing Page and redirect on login
Lambda-School-Labs/cityspire-b-fe pull request #1
Opened 2021-01-28 03:45 UTC by SMoore3773

Routed to landing page on main page load.
Reroute to homepage on successful login.
[Trello Card](https://trello.com/c/v7RN8vIp)

Line 45 of index.js for the main app has a linting error because of the way that okta is storing it's token.

Changed title of login screen to reflect City Spire app

2021-01-28 20:34 UTC, allyjay317 commented on src/components/pages/Landing/RenderLandingPage.js
> +
Is this intended to be reusable or have anything added to it later? or would it be good to do inline on line 27 instead?

2021-01-28 20:38 UTC, allyjay317 requested changes
Generally looks good, possibly move the homepagePushHandler to a useEffect instead?

2021-01-29 08:27 UTC, allyjay317 approved these changes
Looking good!

2021-01-30 01:42 UTC, songamugenzi approved these changes

2021-01-30 02:10 UTC, merged

2021-02-13 03:49 UTC, allyjay317 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Landing Page](https://trello.com/c/Zq1DwK4V/36-create-landing-page)

2021-02-13 03:50 UTC, allyjay317 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create unprotected landing page](https://trello.com/c/v7RN8vIp/34-create-unprotected-landing-page)