Menu bar
Lambda-School-Labs/cityspire-b-fe pull request #3
Opened 2021-02-03 05:08 UTC by SMoore3773

------------------
[Pin Saving Trello Card](https://trello.com/c/JwBCYKrE)
-------------------------
### Location:
-MenuContainer.js
-RenderMenu.js
-RenderHomePage.js
### Details:
1) Created a menu bar component that has some navigation functionality and working OKTA logout function.
-------------------------
## Committed Features:
1 | Modular menu component
2 | Working redirect to login page
3 | Working OKTA logout and redirect to landing on logout

2021-02-03 14:07 UTC, allyjay317 requested changes
Made a few comments that should be addressed, but otherwise looks good!

2021-02-03 14:07 UTC, allyjay317 commented on src/components/pages/Home/RenderHomePage.js
> +      <MenuBar authService={authService} />
We should move this outside of the routes so that it shows up regardless of which page you're on

2021-02-03 14:07 UTC, allyjay317 commented on src/components/pages/Home/RenderHomePage.js
> +import { LoadingComponent } from '../../common';
Why are we importing this here, and receiving it in props?

2021-02-04 04:33 UTC, samir-hub submitted a review, later dismissed
The PR is focused and small. Great job using the template! 
We can merge after Allison's concerns are addressed.

2021-02-05 06:18 UTC, songamugenzi approved these changes, later dismissed

2021-02-13 03:45 UTC, allyjay317 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Menu Component](https://trello.com/c/JwBCYKrE/12-menu-component)

2021-02-23 02:54 UTC, allyjay317 approved these changes, later dismissed

2021-02-23 03:36 UTC, samir-hub approved these changes
Great job keeping the PR organized. The PR is focused and easy to review. We want to make sure that the menu is present in all pages.

2021-02-24 02:13 UTC, songamugenzi approved these changes

2021-02-24 02:17 UTC, merged